// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-legacy-cache-purger/clients"
	"github.com/cloudflare/cloudflare-go/v6/cache"
	"github.com/cloudflare/cloudflare-go/v6/option"
	"sync"
)

// Ensure, that CloudflareCacheClienterMock does implement clients.CloudflareCacheClienter.
// If this is not the case, regenerate this file with moq.
var _ clients.CloudflareCacheClienter = &CloudflareCacheClienterMock{}

// CloudflareCacheClienterMock is a mock implementation of clients.CloudflareCacheClienter.
//
//	func TestSomethingThatUsesCloudflareCacheClienter(t *testing.T) {
//
//		// make and configure a mocked clients.CloudflareCacheClienter
//		mockedCloudflareCacheClienter := &CloudflareCacheClienterMock{
//			PurgeFunc: func(ctx context.Context, params cache.CachePurgeParams, opts ...option.RequestOption) (*cache.CachePurgeResponse, error) {
//				panic("mock out the Purge method")
//			},
//		}
//
//		// use mockedCloudflareCacheClienter in code that requires clients.CloudflareCacheClienter
//		// and then make assertions.
//
//	}
type CloudflareCacheClienterMock struct {
	// PurgeFunc mocks the Purge method.
	PurgeFunc func(ctx context.Context, params cache.CachePurgeParams, opts ...option.RequestOption) (*cache.CachePurgeResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Purge holds details about calls to the Purge method.
		Purge []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params cache.CachePurgeParams
			// Opts is the opts argument value.
			Opts []option.RequestOption
		}
	}
	lockPurge sync.RWMutex
}

// Purge calls PurgeFunc.
func (mock *CloudflareCacheClienterMock) Purge(ctx context.Context, params cache.CachePurgeParams, opts ...option.RequestOption) (*cache.CachePurgeResponse, error) {
	if mock.PurgeFunc == nil {
		panic("CloudflareCacheClienterMock.PurgeFunc: method is nil but CloudflareCacheClienter.Purge was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params cache.CachePurgeParams
		Opts   []option.RequestOption
	}{
		Ctx:    ctx,
		Params: params,
		Opts:   opts,
	}
	mock.lockPurge.Lock()
	mock.calls.Purge = append(mock.calls.Purge, callInfo)
	mock.lockPurge.Unlock()
	return mock.PurgeFunc(ctx, params, opts...)
}

// PurgeCalls gets all the calls that were made to Purge.
// Check the length with:
//
//	len(mockedCloudflareCacheClienter.PurgeCalls())
func (mock *CloudflareCacheClienterMock) PurgeCalls() []struct {
	Ctx    context.Context
	Params cache.CachePurgeParams
	Opts   []option.RequestOption
} {
	var calls []struct {
		Ctx    context.Context
		Params cache.CachePurgeParams
		Opts   []option.RequestOption
	}
	mock.lockPurge.RLock()
	calls = mock.calls.Purge
	mock.lockPurge.RUnlock()
	return calls
}
