// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dis-legacy-cache-purger/clients"
	"github.com/slack-go/slack"
	"sync"
)

// Ensure, that SlackClienterMock does implement clients.SlackClienter.
// If this is not the case, regenerate this file with moq.
var _ clients.SlackClienter = &SlackClienterMock{}

// SlackClienterMock is a mock implementation of clients.SlackClienter.
//
//	func TestSomethingThatUsesSlackClienter(t *testing.T) {
//
//		// make and configure a mocked clients.SlackClienter
//		mockedSlackClienter := &SlackClienterMock{
//			PostMessageFunc: func(channel string, options ...slack.MsgOption) (string, string, error) {
//				panic("mock out the PostMessage method")
//			},
//		}
//
//		// use mockedSlackClienter in code that requires clients.SlackClienter
//		// and then make assertions.
//
//	}
type SlackClienterMock struct {
	// PostMessageFunc mocks the PostMessage method.
	PostMessageFunc func(channel string, options ...slack.MsgOption) (string, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// PostMessage holds details about calls to the PostMessage method.
		PostMessage []struct {
			// Channel is the channel argument value.
			Channel string
			// Options is the options argument value.
			Options []slack.MsgOption
		}
	}
	lockPostMessage sync.RWMutex
}

// PostMessage calls PostMessageFunc.
func (mock *SlackClienterMock) PostMessage(channel string, options ...slack.MsgOption) (string, string, error) {
	if mock.PostMessageFunc == nil {
		panic("SlackClienterMock.PostMessageFunc: method is nil but SlackClienter.PostMessage was just called")
	}
	callInfo := struct {
		Channel string
		Options []slack.MsgOption
	}{
		Channel: channel,
		Options: options,
	}
	mock.lockPostMessage.Lock()
	mock.calls.PostMessage = append(mock.calls.PostMessage, callInfo)
	mock.lockPostMessage.Unlock()
	return mock.PostMessageFunc(channel, options...)
}

// PostMessageCalls gets all the calls that were made to PostMessage.
// Check the length with:
//
//	len(mockedSlackClienter.PostMessageCalls())
func (mock *SlackClienterMock) PostMessageCalls() []struct {
	Channel string
	Options []slack.MsgOption
} {
	var calls []struct {
		Channel string
		Options []slack.MsgOption
	}
	mock.lockPostMessage.RLock()
	calls = mock.calls.PostMessage
	mock.lockPostMessage.RUnlock()
	return calls
}
